package com.decipherx;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import io.micronaut.core.type.Argument;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpResponse;
import io.micronaut.http.HttpStatus;
import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@MicronautTest // <1>
class GithubControllerTest {

    private static final List<String> expectedReleases =
        Arrays.asList("Micronaut 3.2.0", "Micronaut 3.1.4", "Micronaut 3.1.3");
    @Inject
    @Client("/")
    HttpClient client; // <2>

    @Test
    public void verifyGithubReleasesCanBeFetchedWithLowLevelHttpClient() {
        //when:
        HttpRequest<Object> request = HttpRequest.GET("/github/releases-lowlevel");

        HttpResponse<List<GithubRelease>> rsp = client.toBlocking()
                                                      .exchange(request, Argument.listOf(GithubRelease.class)); // <4>

        //then: 'the endpoint can be accessed'
        assertEquals(HttpStatus.OK, rsp.getStatus());   // <5>
        assertNotNull(rsp.body()); // <6>

        //when:
        List<GithubRelease> releases = rsp.body();

        //then:
        for (String name : expectedReleases) {
            assertTrue(releases.stream().map(GithubRelease::getName).anyMatch(name::equals));
        }
    }

    @Test
    public void verifyGithubReleasesCanBeFetchedWithCompileTimeAutoGeneratedAtClient() {
        //when:
        HttpRequest<Object> request = HttpRequest.GET("/github/releases-lowlevel");

        List<GithubRelease> githubReleases =
            client.toBlocking().retrieve(request, Argument.listOf(GithubRelease.class)); // <7>

        //then:
        for (String name : expectedReleases) {
            assertTrue(githubReleases.stream().map(GithubRelease::getName).anyMatch(name::equals));
        }
    }
}
